### ISSUE TITLE
EPUB/PDF

### ISSUE THREAD

**Issue by darribas** [marklhc/usc-psyc621-notes#1]
Hello,

First of all congratulations on such a fantastic resource and thank you very much for sharing it online, this is awesome.

I wanted to ask if there's a chance that an ebook/pdf version of the book was added to the website. Currently, there's a button for the download, but it is dead. I've cloned the repo and tried to build them myself but I think the materials on the repo are not enough to compile the book, whether as a website or as an epub. Thanks!

**Comment by marklhc** [comment]
Hi,

Actually here is a web version of it here: https://psyc-bayes-notes.netlify.com/. Thank you for your interest!

Best,

Mark

**Comment by darribas** [comment]
Thanks for answering! However, I cannot find the link to download neither the PDF or the EPUB version. The buttons on your link don't seem to work?

**Comment by marklhc** [comment]
Hi,

I see what you meant. I was able to get an EPUB version with `knitr` so it should be up there now. Thanks for the suggestion!
